# Generated by Django 5.2.7 on 2025-12-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='created_at',
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('student', 'survey'), name='unique_student_survey'),
        ),
    ]
