# Generated by Django 5.2.7 on 2025-12-29 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_surveyresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='category',
            field=models.CharField(choices=[('lesson', '授業について'), ('facility', '施設について'), ('event', '行事について'), ('rules', '校則について'), ('other', 'その他')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.studentid'),
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', '数学'), ('jp', '国語'), ('en', '英語'), ('sci', '理科'), ('soc', '社会'), ('other', 'その他')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.studentid')),
            ],
        ),
    ]
