# Generated by Django 5.2.7 on 2026-01-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_opinion_is_anonymous_opinion_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquestion',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
