# Generated by Django 5.2.7 on 2026-01-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_lessonquestion_answer_lessonquestion_answered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='lessonquestion',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='lessonquestion',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='lessonquestion',
            name='subject',
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='category',
            field=models.CharField(choices=[('lesson', '授業'), ('facility', '施設'), ('event', '行事'), ('other', 'その他')], default='lesson', max_length=20),
        ),
    ]
