# Generated by Django 5.2.7 on 2026-01-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_lessonquestion_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentid',
            name='school_year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
