# Generated by Django 5.2.7 on 2026-01-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_studentid_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentid',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
