# Generated by Django 5.2.7 on 2026-03-03 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_studentid_is_graduated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.IntegerField()),
                ('grade', models.PositiveSmallIntegerField()),
                ('class_num', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='surveyresponse',
            name='unique_student_survey',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='class_num',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='survey',
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='subject',
            field=models.CharField(default='未設定', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentid',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='category',
            field=models.CharField(choices=[('math', '数学'), ('english', '英語'), ('science', '理科'), ('social', '社会'), ('other', 'その他')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='category',
            field=models.CharField(choices=[('lesson', '授業'), ('facility', '施設'), ('event', '行事'), ('rules', '校則'), ('other', 'その他')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.studentid'),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='q_type',
            field=models.CharField(choices=[('text', '自由入力'), ('choice', '選択式')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('student', 'survey')},
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentid'),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'school_year')},
        ),
    ]
