# Generated by Django 5.2.7 on 2026-08-13 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_lessonquestion_is_answered_alter_opinion_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.opinion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentid')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('opinion', 'student'), name='unique_opinion_like')],
            },
        ),
    ]
