# Generated by Django 5.2.7 on 2026-09-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_suspend_reason_report_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_report_per_student_per_target',
        ),
        migrations.RemoveField(
            model_name='studentid',
            name='suspend_reason',
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
